# Generated by Django 4.0 on 2021-12-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(default=models.CharField(max_length=254), max_length=254),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='home/media'),
        ),
    ]
